### ISSUE TITLE
Añadir sección de herramientas para desarrolladores

### ISSUE THREAD

**Issue by cesaralvrz** [Acadeller/recursos-programacion#6]
La idea sería crear otra sección que este dedicada para herramientas que sean útiles para desarrolladores.
Estas podrían estar divididas por sus propias categorías: frontend, backend, data science, git, etc.

**Comment by ibLeDy** [comment]
Buenas, me interesa colaborar con este issue!

**Comment by cesaralvrz** [comment]
Perfecto @ibLeDy, te asigno el issue
