### ISSUE TITLE
Añadir sección de recursos para entrevistas técnicas

### ISSUE THREAD

**Issue by cesaralvrz** [Acadeller/recursos-programacion#7]
La idea sería agregar una sección formada de recursos que ayuden a preparar entrevistas técnicas.

**Comment by Wiki-10** [comment]
Hola! me interesaría realizar esta sección!

**Comment by cesaralvrz** [comment]
Perfecto @Wiki-10, te lo asigno a ti 🚀

**Comment by Wiki-10** [comment]
Listo! ya subí la PR. Espero que los recursos sean de utilidad :)

**Comment by cesaralvrz** [comment]
Feature arreglada en #8
